### ISSUE TITLE
Different language models

### ISSUE THREAD

**Issue by juks** [davidberenstein1957/classy-classification#38] opened 2023-04-05 14:05 UTC
Hi!

Thanks for this library, it really makes complex things simple.

I wonder if some extra effort is required to use other than English models for classification? (English works great out of the box)

Here is some very basic example of wrong classification. Is there a chance somehow to debug and make it work?

```python
import spacy
import classy_classification

nlp = spacy.load("ru_core_news_lg")

data = {
    'right': 'Съешь ещё этих мягких французских булок да выпей чаю.',
    'wrong': 'Быстрая бурая лиса перепрыгивает через ленивую собаку.'
}

nlp.add_pipe(
    'text_categorizer',
    config={
        'data': data,
        'model': 'spacy'
    }
)

test = nlp('Съешь мягких булок')
print(test._.cats)
```

Result is:
`{'right': 0.45482638521673985, 'wrong': 0.5451736147832601}`

It should take the 'right' label, the same way it does for English.

**Comment by davidberenstein1957** [comment] 2023-04-05 14:07
Hi, this is not working because you don't pass a list of examples for each class. Try the following. 

```python
data = {
    'right': ['Съешь ещё этих мягких французских булок да выпей чаю.'],
    'wrong': ['Быстрая бурая лиса перепрыгивает через ленивую собаку.']
}
```

**Comment by juks** [comment] 2023-04-05 14:21
I am sorry for that. Just oversimplified the case from what is was in the actual project.

Will try to make it more related and catch the poing where it gets wrong.

**Comment by juks** [comment] 2023-04-05 15:47
Exact sample used for training - also gives a wrong result:

```python
test = nlp('Съешь ещё этих мягких французских булок да выпей чаю.')
print(test._.cats)
```

Result (expecting 'right'):
```
{'right': 0.22359858914585207, 'wrong': 0.6049628215142842, 'other': 0.17143858933986364}
```

**Comment by davidberenstein1957** [comment] 2023-06-17 10:18
Hi @juks I think it is caused by this issue, will release a fix today. https://github.com/davidberenstein1957/classy-classification/issues/28

**Comment by davidberenstein1957** [comment] 2023-06-18 12:54
This was fixed in version 0.6.3, cheers @juks

**Closed** 2023-06-18 12:55 UTC

**Comment by davidberenstein1957** [comment] 2023-06-19 09:52
Great, you might also want to check https://github.com/davidberenstein1957/spacy-setfit

**Comment by juks** [comment] 2023-06-19 09:55
This is really reasonable for me, since while this ticket was open I had to solve my problem somehow, so I went for Setfit.

Thanks!
